### ISSUE TITLE
Low range of Raspbee II

### ISSUE THREAD

**Issue by mspbonn** [dresden-elektronik/raspbee2-rtc#15]
I'm using a Raspbee II, but the range is very limited. A Osram Power Switch in the next room (distance about 10 m) cannot not be reached. What the reason for that ? The Raspberry II has an original case made of plastic.

**Comment by ChrisHae** [comment]
Are you sure it is because of the range? Is everything else working correctly?
That means have you other devices installed and are they working? Can the switch be paired and is it reachable when it is closer to the gateway? And does the gateway settings page in the phoscon app shows a correct firmware version and not "not connected".

**Comment by mspbonn** [comment]
I have 2 Osram Power Switch connected for test purposes. One very close to the raspberry pi and another in the next room (distance about 10 m). The one in abaout 10 m distance works for several hours and then suddenly no longer communicate with the raspbee ii (no polling events).

Additional info: I have two raspbee ii networks within my house.
