### ISSUE TITLE
Raspberry Pi  unable to compile (kernel 5.10.63-v8+)

### ISSUE THREAD

**Issue by akrilfx** [dresden-elektronik/raspbee2-rtc#18]
Hi everyone,
SInce I have a cron updating my pi every week, I've found out the kernel has been updated recently and the raspbee2 was not streaming data anymore.
When trying to compile the master (after getting the kernel source), heres the message i got : 
```
Linux raspberrypi 5.10.63-v8+ #1459 SMP PREEMPT

checking deb package dependencies...
i2c-tools
build-essential
raspberrypi-kernel-headers
build rtc module...
make -C /lib/modules/5.10.63-v8+/build M=/tmp/raspbee2-rtc-master modules
make[1]: Entering directory '/home/pi/linux-abff5012ab7ccbe1227b9d0af69697cc592df44c'
arch/arm64/Makefile:25: ld does not support --fix-cortex-a53-843419; kernel may be susceptible to erratum
arch/arm64/Makefile:33: LSE atomics not supported by binutils
  CC [M]  /tmp/raspbee2-rtc-master/rtc-pcf85063.o
gcc: error: unrecognized command line option ‘-mgeneral-regs-only’
make[2]: *** [scripts/Makefile.build:280: /tmp/raspbee2-rtc-master/rtc-pcf85063.o] Error 1
make[1]: *** [Makefile:1825: /tmp/raspbee2-rtc-master] Error 2
make[1]: Leaving directory '/home/pi/linux-abff5012ab7ccbe1227b9d0af69697cc592df44c'
make: *** [Makefile:17: build] Error 2
```

Since then, I am unable to get the raspbee2 working anymore. You're help is much appreciated.

**Comment by akrilfx** [comment]
Installing deCONZ seems to work, but the application keeps rebooting constantly.

**Comment by ChrisHae** [comment]
besides the compilation error you got your raspbee has another problem. The functionality of the RaspBee2 does not depend on the compilation of the source  code. This is only needed for the RTC and I think when you have compiled and installed it one time it is not needed to do anymore.

Also updating the OS should not compromise the functionality of the RaspBee2.

So if you can't connect to deCONZ or deCONZ is loosing the connection repeatedly I would suggest the following:
try to install the newest firmware with GCFFlasher 
https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Update-deCONZ-manually#update-in-raspbian

Disconnect other devices connected to the USB port because they could produce interferences.
